### ISSUE TITLE
Rate Limit Path not working ?

### ISSUE THREAD

**Issue by gogovan-vincentngai** [Kong/docs.konghq.com#2553]
### Summary
Installed via Helm Chart
- kong/kong	Chart 1.14.1    App 2.2    

Deploy KongPlugin Rate Limit
limit_by and path not work as expected 

### Steps To Reproduce

Deploy as below
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: demo-rate
config:
  limit_by: path
  path: /foo
  minute: 10
  policy: redis
  redis_host: redis
  redis_port: 6379
plugin: rate-limiting
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/plugins: "demo-rate"
spec:
  rules:
    - host: demo.xyz.dev
      http:
        paths:
          - backend:
              serviceName: echo
              servicePort: 80
            path: /foo
          - backend:
              serviceName: echo
              servicePort: 80
            path: /bar
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo
  name: echo
spec:
  ports:
  - port: 8080
    name: high
    protocol: TCP
    targetPort: 8080
  - port: 80
    name: low
    protocol: TCP
    targetPort: 8080
  selector:
    app: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo
    spec:
      containers:
      - image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
        name: echo
        ports:
        - containerPort: 8080
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        resources: {}
```

### Expected Result

Load Test `https://demo.xyz.dev/foo` will be appear 429 
Load Test `https://demo.xyz.dev/bar` will never  appear 429 

### Actual Result
Both appear 429
