### ISSUE TITLE
ldap-auth

### ISSUE THREAD

**Issue by thanhtai9606** [Kong/docs.konghq.com#3695]
### Where is the problem?

https://docs.konghq.com/hub/kong-inc/ldap-auth/

### What happened?

I cannot login with auth-ldap
this is my config, I already tried with `attribute: cn, userPrincipalName,...` But not working
```
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-ldap-auth
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config: 
  hide_credentials: true
  ldap_host: 192.168.xxx.xxx
  ldap_port: 389
  start_tls: false
  ldaps: false
  base_dn: dc=becamex,dc=local,dc=com
  verify_ldap_host: false
  attribute: sAMAccountName
  cache_ttl: 60
  header_type: ldap
plugin: ldap-auth
```

### What did you expect to happen?

This is test in postman
`Authorization: ldap ZHVuZy5sdC5jbnR0OjEyMzQ2`
```
This is result error
{
    "message": "Invalid authentication credentials"
}
```

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations
