### ISSUE TITLE
Missing documentation on menu on the Dev Portal configuration files

### ISSUE THREAD

**Issue by rLitto** [Kong/docs.konghq.com#4098]
### Where is the problem?

https://docs.konghq.com/gateway/latest/developer-portal/structure-and-file-types/

### What happened?

We discovered that there is a menu configuration in the portal.cli.conf that is undocumented

### What did you expect to happen?

To find documentation on the `menu` section of the portal.cli.conf

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations

**Comment by rLitto** [comment]
Downloaded the portal files for a new file
```
name: Kong Portal
app_version: 4574611
theme:
  name: base
redirect:
  unauthenticated: login
  unauthorized: unauthorized
  login: dashboard
  logout: ''
  pending_approval: ''
  pending_email_verification: ''

# main menu 
menu:
  - title: Catalog
    url: documentation
    needs_auth: false
  - title: My Apps
    url: applications
    needs_auth: true
  - dynamic_title: user.get("email")
    url: settings
    needs_auth: true
    sub_menu:
      - title: Dashboard
        url: dashboard
        needs_auth: true
      - title: Logout
        url: logout
        needs_auth: true     
  - title: Login
    url: login
    needs_auth: false
    hide_when_authenticated: true
  - title: Sign up
    url: register
    needs_auth: false
    hide_when_authenticated: true
    css_classes:
    - nav-button
    - btn
    - btn-secondary


# main menu if authentication is not enabled in dev portal 
menu_no_auth:
  - title: Catalog
    url: documentation
    needs_auth: false

# menu examples
# menu:    
#   - title: Catalog
#     url: documentation
#     needs_auth: false
#   - title: Public
#     url: partners
#     needs_auth: false
#   - title: Auth
#     url: partners
#     needs_auth: true
#   - title: Auth and role
#     url: partners
#     needs_auth: true
#     needs_role: Partners
#   - title: With submenu
#     url: partners
#     needs_auth: false
#     sub_menu:
#       - title: Sub Entry
#         url: sub-page1
#         needs_auth: false
#       - title: Sub Auth
#         url: sub-page2
#         needs_auth: true     
#   - title: My Apps
#     url: applications
#     needs_auth: true
```
that is used in the `themes/base/partials/menu.html` file used in the `themes/base/partials/header.html`
but there is no reference for the menu
