### ISSUE TITLE
WebSocket Validator YAML Example Incorrect

### ISSUE THREAD

**Issue by deckong** [Kong/docs.konghq.com#5406]
### Where is the problem?

https://docs.konghq.com/hub/kong-inc/websocket-validator/

### What happened?

It looks like the YAML examples in the WebSocket Vaidator Plugin are not properly formatted or syntax is incorrect. This gives a schema error.

```
plugins:
- name: websocket-validator
  service: SERVICE_NAME|SERVICE_ID
  config: 
    client:
      text:
      schema: '{ "type": "object" }'
    client:
      text:
      type: 'draft4'
```

### What did you expect to happen?

Believe it should look like the following, which is able to be applied with no errors:

```
plugins:
- name: websocket-validator
  service: SERVICENAME
  config:
    client:
      text:
        schema: '{ "type": "object", "required": ["name"] }'
        type: draft4
```

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations
