### ISSUE TITLE
Improve Gateway API concerning protocol: HTTPS

### ISSUE THREAD

**Issue by jeromeguillaume** [Kong/docs.konghq.com#7132]
### Where is the problem?

https://docs.konghq.com/kubernetes-ingress-controller/latest/concepts/gateway-api/#gateway-management

### What happened?

About the `protocol: HTTPS` property in the example, it lacks the `tls` and `hostname` properties. I guess it also concerns  the `protocol: TLS`

1. If we don't put the `tls` property, there is an error message in the console when we do `kubectl apply`: `Invalid value: "array": tls must be specified for protocols ['HTTPS', 'TLS']`
2.If don't put the `hostname` property, there is an error message in the Ingress Controller pod: `["must be a valid hostname with a wildcard prefix '*' ornwithout"],"type":"ERROR_TYPE_FIELD"}])`

### What did you expect to happen?

Having a `HTTPS` and `TLS` proper example like this:

1) Create a `kong-secret-proxy` with `kubectl create secret tls`
2)
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kong
  namespace: kong
spec:
  gatewayClassName: kong
  listeners:
  - name: proxy-kong
    port: 80
    protocol: HTTP
  - name: proxy-kong-tls
    port: 443
    protocol: HTTPS
    hostname: kong.client.com
    tls:
      mode: Terminate
      certificateRefs:
        - kind: Secret
          group: 
          name: kong-secret-proxy
    allowedRoutes:
      namespaces:
        from: All

```

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations
