### ISSUE TITLE
Parameters in "Basic configuration examples" do not exist

### ISSUE THREAD

**Issue by imurata** [Kong/docs.konghq.com#7655]
### Where is the problem?

https://docs.konghq.com/hub/kong-inc/ai-rate-limiting-advanced/how-to/basic-example/

### What happened?

I followed the example and ran the deck command, but got an error.
```
Error: validate entity 'plugins (ai-rate-limiting-advanced)': HTTP status 400 (message: "3 schema violations (config.llm_providers: required field missing; config.model_providers: unknown field; config.model_providers_limit: unknown field)")
```
Parameters in "Declarative (YAML)" are not present in the configuration reference.
```
  config:
    model_providers:
    - openai
    - mistral
    model_providers_limit:
    - 1000
    - 100
    models_providers_window_size:
    - 3600
    - 60
```

### What did you expect to happen?

Modify the example to use the parameters in the configuration reference.

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations
