### ISSUE TITLE
Failed to deploy due to uncorrect Image Tag

### ISSUE THREAD

**Issue by imurata** [Kong/docs.konghq.com#8304]
### Where is the problem?

https://docs.konghq.com/gateway-operator/1.4.x/get-started/kic/create-gateway/

### What happened?

I copied and ran the GatewayConfiguration for **On-Prem** and got the following error.
```sh
  Warning  Failed     14s (x3 over 53s)  kubelet            Failed to pull image "kong:3.9.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/library/kong:3.9.0": failed to resolve reference "docker.io/library/kong:3.9.0": docker.io/library/kong:3.9.0: not found
```
The following tag is incorrect.
```yaml
          containers:
          - name: proxy
            image: kong:3.9.0
```

### What did you expect to happen?

It should be stated as follows
```yaml
          containers:
          - name: proxy
            image: kong/kong:3.9.0
```

### Code of Conduct and Community Expectations

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to abide by the Community Expectations
